(function () {
  "use strict";

  /* If the URL has a hash we'll be landing on, stop the browser from doing
     its own auto scroll-restoration / hash jump — we dock to header+gap
     ourselves. Set as early as possible (this deferred script runs before
     DOMContentLoaded) so it takes effect before the browser scrolls. */
  if (history.scrollRestoration && location.hash) {
    history.scrollRestoration = "manual";
  }

  /* Deep-linking for stacked-block pages (project pages and other content
     pages whose blocks are vertically stacked <section>s).

     - On load, scrolls to the block named in the URL hash (if any), docked
       just below the fixed header with a small gap — so a shared #link opens
       the page on the right block.
     - On project pages, clicking a section heading copies that section's
       deep-link to the clipboard (silently) — this replaces scroll-driven
       hash updates.

     Pages that own their own hash logic are skipped:
       - homepage ([data-home-root]) -> home.js manages #resume/#studio/#contact
       - tabbed project pages ([data-project-tablist]) -> main.js manages #<tab>
         (and handles heading click-to-copy for tabs)
       - home tablists ([data-home-tablist])
     On JSON-rendered project pages (project.html), render.js assigns a slug id
     to each top-level block and dispatches "vch:project-rendered" once built;
     this module also listens for that event so it can run after the async
     render. */

  function pageMain() {
    return document.querySelector("main");
  }

  function isProjectPage(main) {
    return !!(main && /\bproject-page--/.test(main.className || ""));
  }

  function collectBlocks(main) {
    var blocks = [];
    if (!main) return blocks;
    [].slice.call(main.children).forEach(function (child) {
      var anchor = child.id || "";
      if (!anchor) {
        if (child.tagName !== "SECTION") return;
        var heading = child.querySelector("h1[id], h2[id], h3[id]");
        anchor = heading ? heading.id : "";
      }
      if (anchor) blocks.push({ el: child, anchor: anchor });
    });
    /* Individual spoiler <details> get their own anchor ids (render.js), but
       they sit inside .project-page-spoilers wrappers, so collect them too so
       landing can target a specific spoiler. */
    [].slice.call(main.querySelectorAll("details.spoiler[id]")).forEach(function (d) {
      blocks.push({ el: d, anchor: d.id });
    });
    return blocks;
  }

  function copyLinkToClipboard(hash) {
    var base = location.href.split("#")[0];
    var full = base + (hash ? "#" + hash : "");
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(full).catch(function () {});
      return;
    }
    try {
      var ta = document.createElement("textarea");
      ta.value = full;
      ta.setAttribute("readonly", "");
      ta.style.position = "fixed";
      ta.style.top = "0";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    } catch (e) {}
  }

  function flashCopied(el) {
    if (!el) return;
    el.style.transition = "opacity 0.15s ease";
    el.style.opacity = "0.45";
    setTimeout(function () {
      el.style.opacity = "";
      setTimeout(function () { el.style.transition = ""; }, 170);
    }, 150);
  }

  var initialized = false;
  function init() {
    if (initialized) return;
    /* Skip pages that manage their own hash. */
    if (document.querySelector("[data-home-root], [data-project-tablist], [data-home-tablist]")) return;

    var main = pageMain();
    var blocks = collectBlocks(main);
    if (blocks.length === 0) return;
    initialized = true;

    var headerEl = document.querySelector(".site-header");
    function headerH() { return headerEl ? headerEl.getBoundingClientRect().height : 72; }
    var LANDING_GAP = 24;

    function scrollToAnchor(el) {
      if (!el) return;
      var top = el.getBoundingClientRect().top + window.scrollY - headerH() - LANDING_GAP;
      window.scrollTo(0, Math.max(0, top));
    }

    /* Landing: scroll to the block whose anchor matches the URL hash. The ids
       are either hand-written in the HTML or generated by render.js after
       load, so the browser's native hash jump may miss them — we scroll
       ourselves and keep re-docking until layout is truly settled.

       Why stable-then-finish: a naive single scrollToAnchor (even after a
       couple of rAF) misses LATE shifts — above all the web-font swap, which
       on Ctrl+Shift+R (no cache) lands from the network long after a cached F5
       would have swapped it. That swap reflows the blocks ABOVE the target
       (hero, about, responsibilities) and shifts the target heading UP after
       the single scroll already ran — leaving the inner content
       (vch-player__now / video-scroller__viewport) flush at the top instead of
       the heading. So we use a closed-loop dock (measure the heading's ACTUAL
       viewport position, nudge to header+gap) and only end once nothing has
       moved for STABLE_MS — and fonts are loaded and the entrance animation
       has had time to finish. ResizeObserver on the target + <main> re-docks
       through any late shift. Add ?debug=1 to the URL to log every dock. */
    var DEBUG = /[?&]debug=1(?=&|$)/.test(location.search);
    var key = location.hash.replace(/^#/, "");
    if (key) {
      var hit = blocks.filter(function (b) { return b.anchor === key; })[0];
      var target = hit ? hit.el : document.getElementById(key);
      if (target) {
        var landing = true;
        var landingRaf = 0;
        var landingRO = null;
        var stableTimer = 0;
        var landingStart = performance.now();
        var fontsReady = false;
        var STABLE_MS = 250;
        var MIN_HOLD_MS = 1500;
        var inputAbort = null;
        document.documentElement.style.scrollBehavior = "auto";
        function dbg(msg, extra) {
          if (!DEBUG) return;
          try { console.log("[dlink " + ((performance.now() - landingStart) | 0) + "ms] " + msg, extra || ""); } catch (e) {}
        }
        /* Dock the heading (or the block) to header+gap with a single scroll op.
           Never mix panel-based scrollTo + heading-based scrollBy — that was the
           source of the visible 2-3 jumps. minDelta: skip tiny sub-pixel noise. */
        function dockHeading(reason, minDelta) {
          if (!landing) return;
          var heading = target.querySelector("h1, h2, h3");
          var anchorEl = heading || target;
          var want = headerH() + LANDING_GAP;
          var cur = anchorEl.getBoundingClientRect().top;
          var delta = cur - want;
          var threshold = minDelta != null ? minDelta : 2;
          var moved = false;
          if (Math.abs(delta) >= threshold) {
            window.scrollBy(0, delta);
            moved = true;
          }
          if (DEBUG) {
            dbg(reason, {
              anchor: key,
              heading: heading ? (heading.id || heading.tagName) : null,
              headingTop: Math.round(cur),
              want: want,
              delta: Math.round(delta),
              moved: moved,
              scrollY: Math.round(window.scrollY),
              fontsReady: fontsReady
            });
          }
          armStable();
        }
        /* One synchronous dock before first paint — blocks the native #hash flash. */
        dockHeading("sync", 0);
        function cancelLanding() {
          landing = false;
          if (landingRaf) { try { cancelAnimationFrame(landingRaf); } catch (e) {} landingRaf = 0; }
          if (stableTimer) { try { clearTimeout(stableTimer); } catch (e) {} stableTimer = 0; }
          if (landingRO) { try { landingRO.disconnect(); } catch (e) {} landingRO = null; }
          if (inputAbort) { try { inputAbort(); } catch (e) {} inputAbort = null; }
          document.documentElement.style.scrollBehavior = "";
        }
        function maybeFinish() {
          if (!landing) return;
          var elapsed = performance.now() - landingStart;
          if (fontsReady && elapsed >= MIN_HOLD_MS) {
            dbg("finish (stable " + STABLE_MS + "ms, fontsReady, " + (elapsed | 0) + "ms)");
            dockHeading("final", 4);
            cancelLanding();
          } else {
            armStable();
          }
        }
        function armStable() {
          if (stableTimer) clearTimeout(stableTimer);
          stableTimer = setTimeout(function () { stableTimer = 0; maybeFinish(); }, STABLE_MS);
        }
        function scheduleLandScroll() {
          if (!landing || landingRaf) return;
          landingRaf = requestAnimationFrame(function () { landingRaf = 0; dockHeading("obs", 3); });
        }
        function onUserInput() { if (landing) cancelLanding(); }
        var inputEvents = ["wheel", "touchstart", "touchmove", "keydown", "mousedown"];
        inputEvents.forEach(function (t) { window.addEventListener(t, onUserInput, { passive: true, capture: true }); });
        inputAbort = function () {
          inputEvents.forEach(function (t) { window.removeEventListener(t, onUserInput, { capture: true }); });
        };
        /* Set up the ResizeObserver IMMEDIATELY (synchronously) so any layout
           shift — font swap, image decode, async player/scroller init — is
           corrected IN-FRAME. The ResizeObserver callback runs after layout,
           before paint, so the user never sees the drifted state — only the
           corrected one. This replaces the spread-out periodic macrotask
           re-docks, which each landed at a slightly different position as
           layout drifted and produced the visible 2-3 jumps. */
        if (typeof ResizeObserver !== "undefined") {
          landingRO = new ResizeObserver(function () { scheduleLandScroll(); });
          landingRO.observe(target);
          var mainEl = pageMain();
          if (mainEl) landingRO.observe(mainEl);
        }
        armStable();
        /* fonts.ready / window.load: mark fonts ready so the finish gate can
           close, and act as a safety re-dock in case the observer missed a
           shift. Normally a no-op (the observer already corrected in-frame),
           so no visible jump. */
        try {
          if (document.fonts && document.fonts.ready) {
            document.fonts.ready.then(function () {
              requestAnimationFrame(function () {
                requestAnimationFrame(function () {
                  if (!landing) return;
                  fontsReady = true;
                  dockHeading("fonts", 5);
                });
              });
            });
          } else {
            fontsReady = true;
          }
        } catch (eF) { fontsReady = true; }
        if (document.readyState === "complete") {
          fontsReady = true;
        } else {
          window.addEventListener("load", function () {
            if (!landing) return;
            fontsReady = true;
            dockHeading("load", 5);
          });
        }
        /* Hard cap so a never-resolving fonts.ready / endless resize can't
           hold the scroll-behavior override forever. */
        setTimeout(function () { if (landing) cancelLanding(); }, 10000);
        dbg("armed; anchor=" + key + " readyState=" + document.readyState);
      }
    }

    /* Click a section heading -> copy that section's deep-link to the
       clipboard. Projects only. Silent copy, faint flash on the heading. */
    if (isProjectPage(main)) {
      blocks.forEach(function (b) {
        /* Spoiler <details> are handled by main.js (click the summary label to
           copy) — skip them here so we don't grab an h3 from inside the body. */
        if (b.el.matches && b.el.matches("details.spoiler")) return;
        var heading = b.el.querySelector("h1, h2, h3");
        if (!heading) return;
        heading.style.cursor = "pointer";
        heading.style.userSelect = "none";
        heading.style.webkitUserSelect = "none";
        heading.style.webkitTouchCallout = "none";
        heading.style.webkitTapHighlightColor = "transparent";
        heading.title = "Copy link to this section";
        heading.addEventListener("click", function () {
          copyLinkToClipboard(b.anchor);
          flashCopied(heading);
        });
      });
    }
  }

  document.addEventListener("vch:project-rendered", init);
  document.addEventListener("DOMContentLoaded", init);
  if (document.readyState !== "loading") init();
})();
